from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional

try:
    from jsonschema import Draft7Validator
except ImportError as e:
    raise ImportError(
        "Missing dependency: jsonschema. Install it with: pip install jsonschema"
    ) from e


def _load_json(path: Path) -> Dict[str, Any]:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"JSON file not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _load_schema(schema_path: Path) -> Dict[str, Any]:
    schema_path = Path(schema_path)
    if not schema_path.exists():
        raise FileNotFoundError(f"Schema not found: {schema_path}")
    schema = _load_json(schema_path)

    # Be conservative: default to Draft-07 if not specified (your schemas use draft-07)
    if "$schema" not in schema:
        schema["$schema"] = "http://json-schema.org/draft-07/schema#"
    return schema


def validate_json_file(instance_path: str | Path, schema_path: str | Path) -> None:
    """
    Validate a JSON file against a JSON Schema.
    Raises ValueError with a readable message if validation fails.
    """
    instance_path = Path(instance_path)
    schema_path = Path(schema_path)

    instance = _load_json(instance_path)
    schema = _load_schema(schema_path)

    validator = Draft7Validator(schema)
    errors = sorted(validator.iter_errors(instance), key=lambda e: e.path)

    if errors:
        lines = [f"Schema validation failed for: {instance_path.name}"]
        lines.append(f"Schema: {schema_path.as_posix()}")
        for err in errors[:20]:
            loc = "$"
            if err.path:
                loc += "." + ".".join(str(x) for x in err.path)
            lines.append(f"- {loc}: {err.message}")
        if len(errors) > 20:
            lines.append(f"... and {len(errors) - 20} more errors")
        raise ValueError("\n".join(lines))


def validate_run_artifacts(
    *,
    run_dir: str | Path,
    schemas_dir: str | Path = "schemas",
    validate_manifest: bool = True,
    validate_qc_report: bool = True,
) -> None:
    """
    Validate the key run artifacts generated by A2 inside a run directory.

    Expected files (if enabled):
      - run_manifest.json  against schemas/run_manifest.schema.json
      - qc_report.json     against schemas/qc_report.schema.json (optional – only if you add that schema later)

    Note:
      You currently have schemas for:
        - input_elements.schema.json
        - final_engineering_report.schema.json
        - run_manifest.schema.json
      There is no qc_report.schema.json in your repo (yet), so qc_report validation is skipped automatically.
    """
    run_dir = Path(run_dir)
    schemas_dir = Path(schemas_dir)

    if validate_manifest:
        manifest = run_dir / "run_manifest.json"
        manifest_schema = schemas_dir / "run_manifest.schema.json"
        validate_json_file(manifest, manifest_schema)

    if validate_qc_report:
        qc = run_dir / "qc_report.json"
        qc_schema = schemas_dir / "qc_report.schema.json"
        if qc.exists() and qc_schema.exists():
            validate_json_file(qc, qc_schema)
        # else: silently skip (schema not defined yet)
